name: Release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: ./.github/actions/create-github-release
        with:
          milestone: "0.21.0"
          token: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
